# **REDES NEURAIS RECORRENTES**


*LINKS:*

- Início -> https://www.youtube.com/watch?v=AsNTP8Kwu80&t=189s
- Implementando -> https://www.youtube.com/watch?v=4wuIOcD1LLI
- Notion -> https://www.notion.so/Recurrent-Neural-Network-175134de6f9c8085bfaafe6dc8ae7cf4?source=copy_link


**O que é:**

- É um modelo de deep learning treinado para processar e converter uma entrada de dados sequencial em uma saída de dados sequencial específica. Dados sequenciais pressupõe dados de séries temporais.

- Assim como as RNA básicas, uma RNN é composta de Camadas (entrada/oculta/saída), neurônios, função de ativação, pesos e bias. A grande diferença está na utilização de *loops* de *feedback*.

**Compartilhamento de parâmetros:**

- Os parâmetros são compartilhados entre as etapas de um sequência

In [108]:
import numpy as np
import pandas as pd

In [109]:
df = pd.read_csv("clean_weather.csv") # Dados meteorológicos
df = df.ffill()
df

Unnamed: 0  tmax  tmin  rain  tmax_tomorrow
0      1970-01-01  60.0  35.0   0.0           52.0
1      1970-01-02  52.0  39.0   0.0           52.0
2      1970-01-03  52.0  35.0   0.0           53.0
3      1970-01-04  53.0  36.0   0.0           52.0
4      1970-01-05  52.0  35.0   0.0           50.0
...           ...   ...   ...   ...            ...
13504  2022-11-22  62.0  35.0   0.0           67.0
13505  2022-11-23  67.0  38.0   0.0           66.0
13506  2022-11-24  66.0  41.0   0.0           70.0
13507  2022-11-25  70.0  39.0   0.0           62.0
13508  2022-11-26  62.0  41.0   0.0           64.0

[13509 rows x 5 columns]

In [110]:
df["tmax"].head(10)

0    60.0
1    52.0
2    52.0
3    53.0
4    52.0
5    50.0
6    52.0
7    56.0
8    54.0
9    57.0
Name: tmax, dtype: float64

**Explicando que a quantidade de entradas podem mudar**

In [111]:
df["tmax"].head(10).to_numpy()[np.newaxis,:] #Transforma array (X,1) em (1,X)

array([[60., 52., 52., 53., 52., 50., 52., 56., 54., 57.]])

In [112]:
df["tmax"].head(8).to_numpy()[np.newaxis,:]

array([[60., 52., 52., 53., 52., 50., 52., 56.]])

In [113]:
df["tmax"].head(12).to_numpy()[np.newaxis,:]

array([[60., 52., 52., 53., 52., 50., 52., 56., 54., 57., 57., 58.]])

**RNN mais simples**
- Funcionamento do compartilhamento de parâmetros

In [114]:
np.random.seed(0) # Ao inicializar uma matriz de pesos, ela sempre tem a mesma inicialização

i_weigth = np.random.rand(1,2) # Inicializando pesos de entrada como números aleatórios no shape de 1 linha e 2 colunas.
h_weigth = np.random.rand(2,2) # Inicializando pesos de camada oculta como números aleatórios no shape de 2 linha e 2 colunas.
o_weigth = np.random.rand(2,1) # Inicializando pesos de camada oculta como números aleatórios no shape de 2 linha e 2 colunas.

temps = df["tmax"].tail(3).to_numpy() # Pegando os 3 últimos dados de temperatura máx
temps


array([66., 70., 62.])

In [115]:
x0 = temps[0].reshape(1,1)
x1 = temps[1].reshape(1,1)
x2 = temps[2].reshape(1,1)

In [ ]:
# Equação da camada de entrada na primeira situação
xi_0 = x0 @ i_weigth # "@" multiplicação de matrizes
print(f'xi_0 = ', xi_0)

# Após função de ativação
xh_0 = np.maximum(0,xi_0) # Relu
print(f'xh_0 = ', xh_0)

# Equação de saída primeira situação
xo_0 = xh_0 @ o_weigth  
print(f'xo_0 = ', xo_0)

xi_0 =  [[36.22169126 47.20249818]]
xh_0 =  [[36.22169126 47.20249818]]
xo_0 =  [[57.94406231]]
